- name: Build iOS Action
  uses: sparkfabrik/ios-build-action@v1.2.0
  with:
    project-path: project/ios/project.xcodeproj
      p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
      p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
      mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
      code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
      team-id: ${{ secrets.TEAM_ID }}
      workspace-path: App.xcworkspace # optional